// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
dotenv.config({ override: true });
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Direct connection for migrations (bypasses PgBouncer)
    // Runtime uses adapter-pg with DATABASE_URL in lib/db/prisma.ts
    url: env("DIRECT_URL"),
  },
});
